### ISSUE TITLE
[Bug] Comment on honeypots_public_ips.csv causes error 

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/AIP#18]
The following error was solved by removing the comment line on the honeypots_public_ips.csv (renamed from honeypots_public_ips_example.csv) file:
https://github.com/stratosphereips/AIP/blob/1356877f13d4667716857d6b4956a8628031b641/data/external/honeypots_public_ips_example.csv#L1

Error:
```bash
docker run --rm -v ${PWD}:/home/aip/AIP -v /opt/zeek/logs/:/home/aip/AIP/data/raw:ro -v ${PWD}/data/:/home/aip/AIP/data/:rw --name aip aip:latest bin/aip
2023-07-28 16:28:45,093 - aip.data.access - DEBUG - Creating attacks for dates ['2023-07-27']
2023-07-28 16:28:45,093 - aip.data.access - DEBUG - Making  dataset from raw data for dates ['2023-07-27']
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
           ^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 588, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 588, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/data/access.py", line 105, in _process_raw_files
    daily = _process_zeek_files(zeek_files, date)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/data/access.py", line 67, in _process_zeek_files
    ips = _get_honeypot_ips()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/data/access.py", line 63, in _get_honeypot_ips
    ips = honeypots.public_ip.values
          ^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'public_ip'
"""
```

**Comment by jwackito** [comment]
Solved
