### ISSUE TITLE
Error parsing comment on the CSV

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/AIP#20]
There seems to be an error on this line. The comment should be on the `pd.read_csv` not in the `path.join`.

https://github.com/stratosphereips/AIP/blob/2f8a701096e4d4ac825b83d4ea7197435db43091/lib/aip/data/access.py#L53

```python
Traceback (most recent call last):
  File "/home/aip/AIP/bin/aip", line 63, in <module>
    blocklist = alpha.run()
                ^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/models/alpha.py", line 46, in run
    attacks = get_attacks(start, end, usecols=['orig'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/data/access.py", line 202, in get_attacks
    extract_attacks(datesnotready)
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/data/access.py", line 176, in extract_attacks
    process_zeek_files(datesnotready)
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/aip/data/access.py", line 162, in process_zeek_files
    Parallel(n_jobs=12, backend='multiprocessing')(delayed(_process_raw_files)(date) for date in dates)
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 1944, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 1587, in _get_outputs
    yield from self._retrieve()
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 1691, in _retrieve
    self._raise_error_fast()
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 1726, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 735, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/miniconda3/envs/aip/lib/python3.11/site-packages/joblib/parallel.py", line 753, in _return_or_raise
    raise self._result
TypeError: join() got an unexpected keyword argument 'comment'
```

**Comment by jwackito** [comment]
Solved
