### ISSUE TITLE
AIP missing knowledge base

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/AIP#44]
AIP allows to run models for a specific date, but some models require some history (minimum number of data) to run. 

```
2024-10-26 16:04:41,530 - root - ERROR - Error running Prioritize_New model: date value out of range
Traceback (most recent call last):
  File "/home/aip/AIP/bin/aip", line 66, in run_model
    blocklist = aip_model.run(day)
                ^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 176, in run
    self.db = Knowledgebase(load_until=for_date - timedelta(days=1))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 116, in __init__
    self._load_knowledge_until(day)
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 106, in _load_knowledge_until
    self.build(end=datetime.strptime(day, '%Y-%m-%d').date())
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 133, in build
    day = str(end - timedelta(days=days_ago))
              ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: date value out of range
```

**Comment by verovaleros** [comment]
The same happens with two other models:

```
2024-10-26 16:04:46,816 - root - ERROR - Error running Prioritize_Consistent model: date value out of range
Traceback (most recent call last):
  File "/home/aip/AIP/bin/aip", line 66, in run_model
    blocklist = aip_model.run(day)
                ^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 176, in run
    self.db = Knowledgebase(load_until=for_date - timedelta(days=1))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 116, in __init__
    self._load_knowledge_until(day)
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 106, in _load_knowledge_until
    self.build(end=datetime.strptime(day, '%Y-%m-%d').date())
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 133, in build
    day = str(end - timedelta(days=days_ago))
              ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: date value out of range
```

```
2024-10-26 16:04:52,263 - root - ERROR - Error running Random_Forest model: date value out of range
Traceback (most recent call last):
  File "/home/aip/AIP/bin/aip", line 66, in run_model
    blocklist = aip_model.run(day)
                ^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 255, in run
    training, target = self._get_training_target_set(for_date=for_date)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 230, in _get_training_target_set
    target = Knowledgebase(load_until=for_date - timedelta(days=1))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 116, in __init__
    self._load_knowledge_until(day)
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 106, in _load_knowledge_until
    self.build(end=datetime.strptime(day, '%Y-%m-%d').date())
  File "/home/aip/AIP/lib/aip/models/prioritize.py", line 133, in build
    day = str(end - timedelta(days=days_ago))
              ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: date value out of range
```

**Comment by verovaleros** [comment]
This error is not due to the input date exactly, but related to the knowledge_base. The knowledge base is built from the first time you run AIP and forward, not backwards. 

So when telling AIP to run on a previous date, if the knowledge base does not exist, it's not rebuilt and the model fails.

**Comment by verovaleros** [comment]
This affects some models and not all, because the Alpha models (afaik) do not use the knowledge base.

**Comment by verovaleros** [comment]
If the knowledge base is not there, we can probably try to build it automatically, if the data exists.

**Comment by verovaleros** [comment]
As @eldraco pointed out, features in the knowledge base may depend on the features extracted earlier in time. This means it would be wrong to just trigger a 'build knowledge base for this date only'. 

Probably the right approach would be to catch the error, and add an option to trigger rebuild the entire knowledge base.

**Comment by verovaleros** [comment]
Note: Rebuilding the knowledge base is costly (time consuming) so it's not something we want to 'self' trigger.

**Comment by verovaleros** [comment]
The code for building the knowledge base is located in the file `prioritize.py`. This is a model file. It seems the building of the knowledge base and the models are highly coupled.

If we want to call this knowledge base building from the bin/aip, e.g.: `bin/aip --build-kb YYYY-MM-DD`, then we need to be able to access this functions.

One option would be to do some refactoring to decouple this functionality from the models, which can be actually good for long term.

The downside is that it will be a tricky operation and we should be careful of not introducing errors.
